# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -e ."
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python -m uvicorn goldenverba.server.api:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 65"
